### ISSUE TITLE
Can't compile under Nobara Linux w jlobue10's kernel-6.6.3-203.fsync.ally.fc38.x86_64

### ISSUE THREAD

**Issue by dovcharov** [NeroReflex/ROGueENEMY#4]
Hello. I have Asus ROG Ally with Nobara Linux and jlobue10's kernel-6.6.3-203.fsync.ally.fc38.x86_64 installed
After downloading ROGueEnemy source from Github I am trying to compile it by myself using 
mkdir build
cd build
cmake ..
cmake --build .

After running last command I get an error message:
/home/deck/ROGueENEMY/settings.c:3:10: fatal error: libconfig.h: no such file or catalog
    3 | #include <libconfig.h>
      |          ^~~~~~~~~~~~~
compilation aborted

What do I need to add, to make compilation successful? I installed cmake and make packages.

**Comment by NeroReflex** [comment]
You need to add libevdev-devel. However jlobue is distributing precompiled and tested rpm of this project

**Comment by jlobue10** [comment]
I've provided pre-made RPMs and the src RPM [here](https://github.com/jlobue10/ALLY_Nobara_fixes/tree/main). What's nice about the RPM is that I make sure udev rules are installed as well as the `systemd` service. I'd recommend just installing the RPMs, or if you insist, build your own with the src RPM as the starting point.

**Comment by NeroReflex** [comment]
I totally agree. Closing the issue, if you encounter more problems just open another issue.
